from __future__ import annotations

import json
from pathlib import Path
from typing import Any

SCHEMAS: dict[str, dict[str, Any]] = {
    "artifact_ref.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "artifact_ref.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schema_version", "artifact_id", "digest", "media_type", "artifact_schema_version", "size_bytes"],
        "properties": {
            "schema_version": {"const": "artifact_ref.v1"},
            "artifact_id": {"type": "string", "minLength": 1},
            "digest": {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"},
            "media_type": {"type": "string", "minLength": 1},
            "artifact_schema_version": {"type": "string", "minLength": 1},
            "size_bytes": {"type": "integer", "minimum": 0},
        },
    },
    "active_binding.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "active_binding.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schema_version", "binding_key", "bundle_digest", "generation", "updated_at"],
        "properties": {
            "schema_version": {"const": "active_binding.v1"},
            "binding_key": {"type": "string", "minLength": 1},
            "bundle_digest": {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"},
            "generation": {"type": "integer", "minimum": 1},
            "updated_at": {"type": "string", "minLength": 1},
        },
    },
    "execution_envelope.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "execution_envelope.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schema_version", "execution_status", "domain_outcome", "failure", "session_id", "bundle_digest"],
        "properties": {
            "schema_version": {"const": "execution_envelope.v1"},
            "execution_status": {"enum": ["completed", "blocked", "runtime_failure"]},
            "domain_outcome": {"type": ["object", "null"]},
            "failure": {"type": ["object", "null"]},
            "session_id": {"type": "string", "minLength": 1},
            "bundle_digest": {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"},
        },
    },
    "compiler_stage_result.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "compiler_stage_result.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema_version",
            "build_id",
            "stage_id",
            "status",
            "input_refs",
            "output_refs",
            "issue_refs",
            "evidence_request_refs",
            "quarantined_item_refs",
            "model_call_refs",
            "deterministic_tool_refs",
            "metrics",
            "next_action",
        ],
        "properties": {
            "schema_version": {"const": "compiler_stage_result.v1"},
            "build_id": {"type": "string"},
            "stage_id": {"type": "string"},
            "status": {"enum": ["complete", "partial", "blocked", "rejected"]},
            "input_refs": {"type": "array", "items": {"type": "object"}},
            "output_refs": {"type": "array", "items": {"type": "object"}},
            "issue_refs": {"type": "array", "items": {"type": "object"}},
            "evidence_request_refs": {"type": "array", "items": {"type": "object"}},
            "quarantined_item_refs": {"type": "array", "items": {"type": "object"}},
            "model_call_refs": {"type": "array", "items": {"type": "object"}},
            "deterministic_tool_refs": {"type": "array", "items": {"type": "object"}},
            "metrics": {"type": "object"},
            "next_action": {"enum": ["continue", "acquire_evidence", "rebuild", "stop"]},
        },
    },
    "source_ref.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "source_ref.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schema_version", "source_id", "uri", "adapter_type", "visibility", "metadata"],
        "properties": {
            "schema_version": {"const": "source_ref.v1"},
            "source_id": {"type": "string", "minLength": 1},
            "uri": {"type": "string", "minLength": 1},
            "adapter_type": {"enum": ["expert-document", "requirements", "osv-snapshot", "build-cases"]},
            "visibility": {"enum": ["build", "dev", "runtime", "heldout"]},
            "metadata": {"type": "object"},
        },
    },
    "evidence_unit.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "evidence_unit.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema_version",
            "evidence_id",
            "source_id",
            "source_snapshot_digest",
            "content",
            "content_type",
            "locator",
            "attributes",
        ],
        "properties": {
            "schema_version": {"const": "evidence_unit.v1"},
            "evidence_id": {"type": "string", "minLength": 1},
            "source_id": {"type": "string", "minLength": 1},
            "source_snapshot_digest": {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"},
            "content": {"type": "string", "minLength": 1},
            "content_type": {"type": "string", "minLength": 1},
            "locator": {"type": "object"},
            "attributes": {"type": "object"},
        },
    },
    "knowledge_ir.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "knowledge_ir.v1",
        "type": "object",
        "additionalProperties": False,
        "required": ["schema_version", "domain_id", "nodes", "quarantined_nodes", "source_snapshot_digests"],
        "properties": {
            "schema_version": {"const": "knowledge_ir.v1"},
            "domain_id": {"type": "string", "minLength": 1},
            "nodes": {"type": "array", "items": {"type": "object"}},
            "quarantined_nodes": {"type": "array", "items": {"type": "object"}},
            "source_snapshot_digests": {"type": "array", "items": {"type": "string", "pattern": "^sha256:"}},
        },
    },
    "skill_ir.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "skill_ir.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema_version",
            "skill_id",
            "version",
            "invocation",
            "workflow",
            "constraints",
            "knowledge_requirements",
            "exceptions",
            "source_node_ids",
        ],
        "properties": {
            "schema_version": {"const": "skill_ir.v1"},
            "skill_id": {"type": "string", "minLength": 1},
            "version": {"type": "string", "minLength": 1},
            "invocation": {"type": "object"},
            "workflow": {"type": "array", "items": {"type": "object"}},
            "constraints": {"type": "array", "items": {"type": "object"}},
            "knowledge_requirements": {"type": "array", "items": {"type": "object"}},
            "exceptions": {"type": "array", "items": {"type": "object"}},
            "source_node_ids": {"type": "array", "items": {"type": "string"}},
        },
    },
    "knowledge_projection.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "knowledge_projection.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema_version",
            "projection_id",
            "expert_evidence_refs",
            "structured_snapshot_refs",
            "query_contracts",
            "source_node_ids",
        ],
        "properties": {
            "schema_version": {"const": "knowledge_projection.v1"},
            "projection_id": {"type": "string", "minLength": 1},
            "expert_evidence_refs": {"type": "array", "items": {"type": "object"}},
            "structured_snapshot_refs": {"type": "array", "items": {"type": "object"}},
            "query_contracts": {"type": "array", "items": {"type": "object"}},
            "source_node_ids": {"type": "array", "items": {"type": "string"}},
        },
    },
    "release_bundle.v1": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "release_bundle.v1",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema_version",
            "skill_family",
            "knowledge_ir_ref",
            "skill_ir_refs",
            "knowledge_projection_refs",
            "knowledge_access_binding_refs",
            "dependency_manifest_ref",
        ],
        "properties": {
            "schema_version": {"const": "release_bundle.v1"},
            "skill_family": {"type": "string"},
            "compatible_agent_profiles": {"type": "array"},
            "knowledge_ir_ref": {"type": "object"},
            "skill_ir_refs": {"type": "array"},
            "agent_artifact_refs": {"type": "array"},
            "knowledge_projection_refs": {"type": "array"},
            "knowledge_access_binding_refs": {"type": "array"},
            "promotion_verifier_binding_refs": {"type": "array"},
            "runtime_verifier_binding_refs": {"type": "array"},
            "domain_adapter_ref": {"type": "object"},
            "runtime_compiler_ref": {"type": "object"},
            "domain_primitive_refs": {"type": "array"},
            "provider_adapter_refs": {"type": "array"},
            "schema_bundle_ref": {"type": "object"},
            "provider_policy_ref": {"type": "object"},
            "permission_request_ref": {"type": "object"},
            "provenance_manifest_ref": {"type": "object"},
            "dependency_manifest_ref": {"type": "object"},
        },
    },
}


def export_schemas(output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for schema_id, payload in sorted(SCHEMAS.items()):
        path = output_dir / f"{schema_id}.schema.json"
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        paths.append(path)
    return paths
