from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Sequence

from .capability_registry import CAPABILITY_SPECS
from .evidence import write_json, write_text
from .schemas import SkillPackage
from .task_cases import ControlledTaskCase


DISTILLATION_HINTS: dict[str, tuple[str, ...]] = {
    "UPLOAD_TYPE_MAGIC": ("content validation", "mime", "magic", "magic bytes", "content-type header", "content type", "extension", "file type", "file signature", "signature validation"),
    "UPLOAD_PATH_ISOLATION": ("path isolation", "non-public storage", "storage", "outside webroot", "outside web root", "store the files on a different server", "change the filename", "generated by the application", "rename uploaded files", "rename files", "web root"),
    "UPLOAD_AUDIT_RETENTION": ("audit retention", "audit", "retention", "logging", "log upload", "event logging", "submission and processing of user-generated content", "file uploads"),
    "AUTH_SCOPE_MATRIX": ("role/scope authorization", "role", "scope", "authorization", "access control", "least privilege", "permission", "deny by default", "validate the permissions on every request", "perform access control checks on every request", "authenticated but not authorized"),
    "AUTH_OBJECT_OWNERSHIP": ("object ownership", "ownership", "tenant boundary", "tenant", "object level authorization", "per-record access", "idor", "lookup ids", "user-controlled key"),
    "AUTH_ERROR_ENVELOPE": ("error envelope", "error", "envelope", "avoid revealing", "generic error", "consistent denial", "sensitive information", "error messages", "exit safely when authorization checks fail"),
    "CONFIG_AUDIT_EXPORT": ("audit retention", "export sinks", "export sink", "audit", "logging", "log retention", "centralized logging", "data exports", "security events"),
    "CONFIG_ENV_GUARD": ("separate prod from dev/test", "prod", "dev/test", "debug state", "development", "production", "environment", "hardcoded api key", "hardcoded", "plaintext", "secrets", "environment variable", "debug output"),
    "API_SCHEMA_CONTRACT": ("strict json report contract", "json report contract", "evidence spans", "fix specificity"),
    "API_OVERBROAD_RISK": ("overbroad generic findings", "overbroad", "generic findings"),
    "DATA_REQUIRED_FIELD_COVERAGE": ("missing-column issues", "required field", "row sample"),
    "DATA_TEMPORAL_SPLIT_GUARD": ("temporal split hygiene", "cutoff rule", "offending row id"),
    "DATA_LABEL_ENUM_ALIGNMENT": ("label values", "declared contract", "unexpected label token"),
    "PATCH_TEST_FAILURE_REPRO": ("failing test", "test failure", "regression assertion"),
    "PATCH_MINIMAL_CODE_CHANGE": ("minimal patch", "small source change", "behavior-preserving"),
    "PATCH_REGRESSION_VALIDATION": ("targeted test", "regression validation", "validation command"),
}


@dataclass(frozen=True)
class CapabilityProjection:
    capability_id: str
    title: str
    source_span: str
    matched_keywords: tuple[str, ...]
    score: int
    selected: bool
    source_case_id: str
    task_family: str


@dataclass(frozen=True)
class MaterialSource:
    source_id: str
    task_family: str
    title: str
    material_text: str
    source_url: str | None = None
    source_path: str | None = None
    metadata: dict[str, Any] | None = None


TASK_FAMILY_CAPABILITIES: dict[str, tuple[str, ...]] = {
    "upload_security": ("UPLOAD_TYPE_MAGIC", "UPLOAD_PATH_ISOLATION", "UPLOAD_AUDIT_RETENTION"),
    "config_security": ("CONFIG_AUDIT_EXPORT", "CONFIG_ENV_GUARD"),
    "auth_access_control": ("AUTH_SCOPE_MATRIX", "AUTH_OBJECT_OWNERSHIP", "AUTH_ERROR_ENVELOPE"),
    "api_or_code_review": ("API_SCHEMA_CONTRACT", "API_OVERBROAD_RISK"),
    "data_quality_review": ("DATA_REQUIRED_FIELD_COVERAGE", "DATA_TEMPORAL_SPLIT_GUARD", "DATA_LABEL_ENUM_ALIGNMENT"),
    "software_patch_review": ("PATCH_TEST_FAILURE_REPRO", "PATCH_MINIMAL_CODE_CHANGE", "PATCH_REGRESSION_VALIDATION"),
}


CAPABILITY_REVIEW_RULES: dict[str, str] = {
    "UPLOAD_TYPE_MAGIC": "Report this only when the target trusts extension or Content-Type alone, or when file-signature / magic-byte validation is missing or bypassable.",
    "UPLOAD_PATH_ISOLATION": "Report this only when uploaded content can stay under a public or executable path, or when user-controlled names are written directly without a server-generated storage name.",
    "UPLOAD_AUDIT_RETENTION": "Report this only when upload events lack attributable audit fields, retention, or export/centralization needed for incident review.",
    "AUTH_SCOPE_MATRIX": "Authentication alone is not enough. Report this when the flow checks login state but does not enforce role, scope, or action-level permission before a protected read or mutation.",
    "AUTH_OBJECT_OWNERSHIP": "Report this when object fetch or mutation is not bound to tenant, owner, or relationship constraints for the requested resource.",
    "AUTH_ERROR_ENVELOPE": "Report this when denial responses reveal object identifiers, existence, or sensitive debug context instead of a generic authorization failure envelope.",
    "CONFIG_AUDIT_EXPORT": "Report this when production-facing audit configuration lacks retention, export sink, or sufficient event detail for review and incident response.",
    "CONFIG_ENV_GUARD": "Report this when production-relevant config contains hardcoded secrets, debug-style defaults, or dev/test assumptions that should be isolated from production paths.",
    "API_SCHEMA_CONTRACT": "Report this when the review/report path emits prose or omits required structured fields such as capability_id, evidence_span, or recommended_fix.",
    "API_OVERBROAD_RISK": "Report this when a finding is generic or speculative and not bound to a concrete code or config span.",
    "DATA_REQUIRED_FIELD_COVERAGE": "Report this when required fields are blank or missing in concrete rows that should be validated before downstream use.",
    "DATA_TEMPORAL_SPLIT_GUARD": "Report this when train/validation or historical/future boundaries are violated by concrete row evidence.",
    "DATA_LABEL_ENUM_ALIGNMENT": "Report this when label values fall outside the declared contract or enum.",
    "PATCH_TEST_FAILURE_REPRO": "Report this when the patch path lacks a concrete failing test or regression assertion tied to the claimed bug.",
    "PATCH_MINIMAL_CODE_CHANGE": "Report this when a patch is broader than needed and a smaller behavior-preserving change is available.",
    "PATCH_REGRESSION_VALIDATION": "Report this when the patch path does not preserve a targeted validation command or regression check.",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def material_segments(text: str) -> list[str]:
    normalized = text.replace("\r\n", "\n")
    segments: list[str] = []
    seen: set[str] = set()

    def add_segment(value: str) -> None:
        cleaned = " ".join(value.strip().split())
        if not cleaned or cleaned in seen:
            return
        seen.add(cleaned)
        segments.append(cleaned)

    for block in normalized.split("\n\n"):
        block_text = " ".join(line.strip(" -*\t") for line in block.splitlines() if line.strip())
        add_segment(block_text)
    for line in normalized.splitlines():
        stripped = line.strip(" -*\t")
        if len(stripped) >= 24:
            add_segment(stripped)
    flattened = " ".join(normalized.split())
    if flattened:
        add_segment(flattened)
    return segments


def hint_keywords(capability_id: str) -> tuple[str, ...]:
    spec = CAPABILITY_SPECS[capability_id]
    merged = list(DISTILLATION_HINTS.get(capability_id, ()))
    merged.extend(needle for needle in spec.detector_needles if needle not in merged)
    return tuple(merged)


def project_capability(expert_material: str, capability_id: str, *, case_id: str, task_family: str) -> CapabilityProjection:
    hints = [item.lower() for item in hint_keywords(capability_id)]
    best_clause = expert_material.strip()
    best_hits: list[str] = []
    best_score = (0, 0, 0)
    for clause in material_segments(expert_material):
        lowered = clause.lower()
        hits = [hint for hint in hints if hint in lowered]
        score = (len(hits), sum(len(hit) for hit in hits), -len(clause))
        if score > best_score:
            best_score = score
            best_hits = hits
            best_clause = clause
    spec = CAPABILITY_SPECS[capability_id]
    return CapabilityProjection(
        capability_id=capability_id,
        title=spec.title,
        source_span=best_clause,
        matched_keywords=tuple(best_hits),
        score=best_score[0],
        selected=best_score[0] > 0,
        source_case_id=case_id,
        task_family=task_family,
    )


def project_case_capabilities(case: ControlledTaskCase, allowed_capabilities: Sequence[str] | None = None) -> list[CapabilityProjection]:
    universe = tuple(allowed_capabilities or case.expected_capabilities)
    projections = [project_capability(case.expert_material, capability_id, case_id=case.case_id, task_family=case.task_family) for capability_id in universe]
    selected = [item for item in projections if item.selected]
    if selected:
        return selected
    raise ValueError(f"no capabilities were distilled from expert material for case `{case.case_id}`")


def project_material_capabilities(material: MaterialSource, allowed_capabilities: Sequence[str] | None = None) -> list[CapabilityProjection]:
    universe = tuple(allowed_capabilities or TASK_FAMILY_CAPABILITIES.get(material.task_family, ()))
    if not universe:
        raise ValueError(f"no capability universe registered for task_family `{material.task_family}`")
    projections = [
        project_capability(
            material.material_text,
            capability_id,
            case_id=material.source_id,
            task_family=material.task_family,
        )
        for capability_id in universe
    ]
    selected = [item for item in projections if item.selected]
    if selected:
        return selected
    raise ValueError(f"no capabilities were distilled from material `{material.source_id}`")


def normalize_group_payload(name: str, task_family: str, capabilities: Iterable[str], source_cases: Iterable[str]) -> dict[str, Any]:
    return {
        "name": name,
        "task_families": [task_family] if task_family else [],
        "capabilities": list(dict.fromkeys(str(item) for item in capabilities if str(item).strip())),
        "source_cases": list(dict.fromkeys(str(item) for item in source_cases if str(item).strip())),
    }


def merge_capability_groups(groups: Sequence[dict[str, Any]]) -> list[dict[str, Any]]:
    merged: dict[str, dict[str, Any]] = {}
    order: list[str] = []
    for group in groups:
        name = str(group.get("name") or "")
        if not name:
            continue
        if name not in merged:
            merged[name] = {"name": name, "task_families": [], "capabilities": [], "source_cases": []}
            order.append(name)
        current = merged[name]
        for field in ("task_families", "capabilities", "source_cases"):
            for item in group.get(field, []):
                value = str(item).strip()
                if value and value not in current[field]:
                    current[field].append(value)
    return [merged[name] for name in order]


def projection_index(projections: Sequence[CapabilityProjection]) -> dict[str, list[CapabilityProjection]]:
    index: dict[str, list[CapabilityProjection]] = {}
    for item in projections:
        index.setdefault(item.capability_id, []).append(item)
    return index


def capability_review_rule(capability_id: str) -> str:
    return CAPABILITY_REVIEW_RULES.get(capability_id, "Report this only when the target shows a concrete missing, bypassable, or overly broad control grounded in exact evidence.")


def projection_lessons(items: Sequence[CapabilityProjection]) -> list[str]:
    lessons: list[str] = []
    seen: set[str] = set()
    for item in items:
        snippet = " ".join(item.source_span.strip().split())
        if not snippet:
            continue
        snippet = snippet[:220].rstrip()
        if snippet in seen:
            continue
        seen.add(snippet)
        lessons.append(snippet)
    return lessons[:2]


def render_root_skill_markdown(skill_id: str, versions: Sequence[str], supported_families: Sequence[str]) -> str:
    return "\n".join(
        [
            f"# {skill_id}",
            "",
            "This is an installable Codex Skill bundle generated through expert-material distillation.",
            "",
            "## Closed Loop",
            "",
            "expert materials -> distilled Skill package -> installed runtime execution -> verifier/evidence feedback -> candidate evolution",
            "",
            f"- available_versions: {', '.join(f'`{item}`' for item in versions)}",
            f"- supported_task_families: {', '.join(f'`{item}`' for item in supported_families)}",
            "",
            "## Safety Boundary",
            "",
            "- Defensive review only.",
            "- No exploit generation, no attack-chain execution, no unauthorized target testing.",
            "",
        ]
    ) + "\n"


def render_version_skill_markdown(
    *,
    skill_id: str,
    version: str,
    task_family: str,
    capability_groups: Sequence[dict[str, Any]],
    source_cases: Sequence[str],
    distillation_method: str,
    projection_map: dict[str, list[CapabilityProjection]] | None = None,
) -> str:
    projection_map = projection_map or {}
    lines = [
        f"# {skill_id} Installed Runtime {version}",
        "",
        "This installed runtime was distilled from expert materials, not manually written as a one-off prompt.",
        "",
        "## Distillation Metadata",
        "",
        f"- distillation_method: `{distillation_method}`",
        f"- runtime_task_family: `{task_family}`",
        f"- source_cases: {', '.join(f'`{item}`' for item in source_cases)}",
        "",
        "## Review Protocol",
        "",
        "- Emit findings only for missing, bypassable, unset, overbroad, or leaking controls tied to exact target evidence.",
        "- If the target already implements the active control without an obvious bypass, emit no finding for that capability.",
        "- Do not promote positive observations, implementation praise, or maintenance reminders into findings.",
        "- Evidence spans should be exact complete target lines or exact substrings that normalize to one complete target line.",
        "- Unsupported task families must activate `out_of_scope_guard` and emit no unrelated findings.",
        "",
        "## Capability Groups",
        "",
    ]
    for group in capability_groups:
        lines.append(f"### {group['name']}")
        lines.append(f"- task_families: {', '.join(f'`{item}`' for item in group.get('task_families', [])) or '`none`'}")
        if group.get("source_cases"):
            lines.append(f"- distilled_from: {', '.join(f'`{item}`' for item in group['source_cases'])}")
        lines.append("- capabilities:")
        if group.get("capabilities"):
            for capability_id in group["capabilities"]:
                spec = CAPABILITY_SPECS[capability_id]
                lines.append(f"  - `{capability_id}`: {CAPABILITY_SPECS[capability_id].title}")
                lines.append(f"    - review_rule: {capability_review_rule(capability_id)}")
                lines.append(f"    - evidence_pattern: `{spec.evidence_hint}`")
                lines.append(f"    - fix_shape: {spec.fix_hint}")
                lessons = projection_lessons(projection_map.get(capability_id, []))
                if lessons:
                    for lesson in lessons:
                        lines.append(f"    - distilled_public_lesson: \"{lesson}\"")
        else:
            lines.append("  - none")
        lines.append("")
    lines.extend(
        [
            "## Output Contract",
            "",
            "- `capability_id`",
            "- `evidence_span`",
            "- `recommended_fix`",
            "",
            "## Safety Boundary",
            "",
            "- Defensive review only.",
            "- Unsupported task families must activate `out_of_scope_guard` and avoid unrelated findings.",
            "",
        ]
    )
    return "\n".join(lines)


def build_root_manifest(
    skill_id: str,
    version: str,
    versions: Sequence[str],
    supported_families: Sequence[str],
    title: str,
    *,
    distillation_method: str = "keyword_projection_from_expert_materials",
) -> dict[str, Any]:
    return {
        "skill_id": skill_id,
        "package_type": "distilled_codex_skill_bundle",
        "created_at": utc_now(),
        "name": title,
        "default_version": version,
        "available_versions": list(versions),
        "supported_task_families": list(supported_families),
        "distillation_method": distillation_method,
        "deployment_shape": "codex_skill_plus_cli",
        "safety_boundary": {
            "allowed": ["defensive_detection", "explanation", "fix_recommendation", "patch_validation"],
            "forbidden": ["exploit_generation", "attack_chain_execution", "unauthorized_target_testing"],
        },
    }


def build_version_manifest(
    *,
    skill_id: str,
    version: str,
    task_family: str,
    capability_groups: Sequence[dict[str, Any]],
    source_cases: Sequence[str],
    distillation_method: str = "keyword_projection_from_expert_materials",
    package_role: str = "expert_distilled_runtime",
) -> dict[str, Any]:
    capabilities: list[str] = []
    supported_families: list[str] = []
    for group in capability_groups:
        for capability_id in group.get("capabilities", []):
            if capability_id not in capabilities:
                capabilities.append(capability_id)
        for family in group.get("task_families", []):
            if family not in supported_families:
                supported_families.append(family)
    package = SkillPackage(
        skill_id=skill_id,
        version=version,
        task_family=task_family,
        capabilities=tuple(capabilities),
        output_contract=("capability_id", "evidence_span", "recommended_fix"),
        trace_contract=("trajectory.jsonl", "target_reads.json", "skill_reads.json"),
        metadata={
            "package_role": package_role,
            "distillation_method": distillation_method,
            "supported_task_families": supported_families,
            "capability_groups": list(capability_groups),
            "source_cases": list(source_cases),
            "out_of_scope_group": "out_of_scope_guard",
            "distillation_provenance_dir": "provenance",
        },
    )
    return package.to_dict()


def distill_skill_bundle(
    *,
    skill_id: str,
    version: str,
    cases: Sequence[ControlledTaskCase],
    output_dir: Path,
    title: str | None = None,
) -> dict[str, Any]:
    if not cases:
        raise ValueError("at least one controlled task case is required for distillation")
    title = title or f"{skill_id} Expert-Distilled Skill"
    output_dir.mkdir(parents=True, exist_ok=True)
    version_dir = output_dir / "versions" / version
    provenance_dir = version_dir / "provenance"

    projections: list[CapabilityProjection] = []
    capability_groups: list[dict[str, Any]] = []
    source_manifest: list[dict[str, Any]] = []
    supported_families: list[str] = []
    for case in cases:
        case_projections = project_case_capabilities(case)
        projections.extend(case_projections)
        selected_capabilities = [item.capability_id for item in case_projections]
        capability_groups.append(normalize_group_payload(case.task_family, case.task_family, selected_capabilities, [case.case_id]))
        source_manifest.append(
            {
                "case_id": case.case_id,
                "title": case.title,
                "task_family": case.task_family,
                "source_dir": case.source_dir,
                "selected_capabilities": selected_capabilities,
                "expert_material_preview": case.expert_material[:240],
            }
        )
        if case.task_family not in supported_families:
            supported_families.append(case.task_family)
    capability_groups = merge_capability_groups(capability_groups)
    capability_groups.append({"name": "out_of_scope_guard", "task_families": [], "capabilities": [], "source_cases": []})
    grouped_projections = projection_index(projections)

    task_family = supported_families[0] if len(supported_families) == 1 else "multi_task_expert_distilled"
    manifest = build_version_manifest(
        skill_id=skill_id,
        version=version,
        task_family=task_family,
        capability_groups=capability_groups,
        source_cases=[case.case_id for case in cases],
    )
    version_skill = render_version_skill_markdown(
        skill_id=skill_id,
        version=version,
        task_family=task_family,
        capability_groups=capability_groups,
        source_cases=[case.case_id for case in cases],
        distillation_method="keyword_projection_from_expert_materials",
        projection_map=grouped_projections,
    )

    existing_root = {}
    root_manifest_path = output_dir / "manifest.json"
    if root_manifest_path.exists():
        import json

        existing_root = json.loads(root_manifest_path.read_text(encoding="utf-8-sig"))
    versions = sorted({*(existing_root.get("available_versions", []) or []), version})
    root_manifest = build_root_manifest(skill_id, version, versions, supported_families, title)

    extracted_candidates = [
        {
            "case_id": item.source_case_id,
            "task_family": item.task_family,
            "capability_id": item.capability_id,
            "title": item.title,
            "source_span": item.source_span,
            "matched_keywords": list(item.matched_keywords),
            "score": item.score,
            "selected": item.selected,
        }
        for item in projections
    ]
    capability_provenance = [
        {
            "capability_id": item.capability_id,
            "title": item.title,
            "task_family": item.task_family,
            "source_case_id": item.source_case_id,
            "source_span": item.source_span,
            "matched_keywords": list(item.matched_keywords),
            "projection_score": item.score,
            "selection_rule": "selected_when_keyword_projection_score_gt_zero",
        }
        for item in projections
    ]
    distillation_trace = {
        "generated_at": utc_now(),
        "skill_id": skill_id,
        "version": version,
        "method": "keyword_projection_from_expert_materials",
        "boundary": "This is a real distillation path for controlled expert materials. It is not an open-world semantic induction claim.",
        "steps": [
            {"stage": "load_source_materials", "artifact": "provenance/source_materials_manifest.json"},
            {"stage": "project_capabilities", "artifact": "provenance/extracted_candidates.json"},
            {"stage": "compile_runtime_manifest", "artifact": "manifest.json"},
            {"stage": "render_skill_text", "artifact": "SKILL.md"},
        ],
    }

    write_text(output_dir / "SKILL.md", render_root_skill_markdown(skill_id, versions, supported_families))
    write_json(output_dir / "manifest.json", root_manifest)
    write_text(
        output_dir / "README.md",
        "\n".join(
            [
                f"# {skill_id}",
                "",
                "This bundle was generated from expert materials through `skill-deploy distill-skill`.",
                "",
                "```powershell",
                f"skill-deploy install --skill {output_dir.as_posix()} --version {version}",
                "```",
                "",
            ]
        )
        + "\n",
    )
    write_text(version_dir / "SKILL.md", version_skill)
    write_json(version_dir / "manifest.json", manifest)
    write_json(
        provenance_dir / "source_materials_manifest.json",
        {
            "sources": source_manifest,
            "source_case_count": len(source_manifest),
            "supported_task_families": supported_families,
        },
    )
    for case in cases:
        write_text(provenance_dir / "source_materials" / f"{case.case_id}.md", case.expert_material + "\n")
    write_json(provenance_dir / "extracted_candidates.json", extracted_candidates)
    write_json(provenance_dir / "capability_provenance.json", capability_provenance)
    write_json(provenance_dir / "distillation_trace.json", distillation_trace)
    write_json(
        output_dir / "eval" / "smoke_cases.json",
        {
            "distilled_skill_id": skill_id,
            "version": version,
            "cases": [
                {
                    "case_id": case.case_id,
                    "command": f"skill-deploy run-skill --installed {skill_id} --case {case.case_id} --backend offline_deterministic",
                }
                for case in cases
            ],
        },
    )
    write_json(
        output_dir / "examples" / "distillation_summary.json",
        {
            "skill_id": skill_id,
            "version": version,
            "source_cases": [case.case_id for case in cases],
            "selected_capability_count": len({item.capability_id for item in projections}),
            "supported_task_families": supported_families,
        },
    )
    return {
        "skill_id": skill_id,
        "version": version,
        "output_dir": str(output_dir),
        "version_dir": str(version_dir),
        "supported_task_families": supported_families,
        "selected_capabilities": sorted({item.capability_id for item in projections}),
        "source_cases": [case.case_id for case in cases],
        "distillation_method": "keyword_projection_from_expert_materials",
    }


def distill_material_skill_bundle(
    *,
    skill_id: str,
    version: str,
    materials: Sequence[MaterialSource],
    output_dir: Path,
    title: str | None = None,
    distillation_method: str = "keyword_projection_from_open_materials",
    package_role: str = "open_material_distilled_runtime",
) -> dict[str, Any]:
    if not materials:
        raise ValueError("at least one material source is required for open-material distillation")
    title = title or f"{skill_id} Open-Material Distilled Skill"
    output_dir.mkdir(parents=True, exist_ok=True)
    version_dir = output_dir / "versions" / version
    provenance_dir = version_dir / "provenance"

    projections: list[CapabilityProjection] = []
    capability_groups: list[dict[str, Any]] = []
    source_manifest: list[dict[str, Any]] = []
    supported_families: list[str] = []
    for material in materials:
        material_projections = project_material_capabilities(material)
        projections.extend(material_projections)
        selected_capabilities = [item.capability_id for item in material_projections]
        capability_groups.append(normalize_group_payload(material.task_family, material.task_family, selected_capabilities, [material.source_id]))
        source_manifest.append(
            {
                "source_id": material.source_id,
                "title": material.title,
                "task_family": material.task_family,
                "source_url": material.source_url,
                "source_path": material.source_path,
                "selected_capabilities": selected_capabilities,
                "material_preview": material.material_text[:240],
                "metadata": dict(material.metadata or {}),
            }
        )
        if material.task_family not in supported_families:
            supported_families.append(material.task_family)
    capability_groups = merge_capability_groups(capability_groups)
    capability_groups.append({"name": "out_of_scope_guard", "task_families": [], "capabilities": [], "source_cases": []})
    grouped_projections = projection_index(projections)

    task_family = supported_families[0] if len(supported_families) == 1 else "multi_task_open_material_distilled"
    manifest = build_version_manifest(
        skill_id=skill_id,
        version=version,
        task_family=task_family,
        capability_groups=capability_groups,
        source_cases=[material.source_id for material in materials],
        distillation_method=distillation_method,
        package_role=package_role,
    )
    version_skill = render_version_skill_markdown(
        skill_id=skill_id,
        version=version,
        task_family=task_family,
        capability_groups=capability_groups,
        source_cases=[material.source_id for material in materials],
        distillation_method=distillation_method,
        projection_map=grouped_projections,
    )

    existing_root = {}
    root_manifest_path = output_dir / "manifest.json"
    if root_manifest_path.exists():
        import json

        existing_root = json.loads(root_manifest_path.read_text(encoding="utf-8-sig"))
    versions = sorted({*(existing_root.get("available_versions", []) or []), version})
    root_manifest = build_root_manifest(skill_id, version, versions, supported_families, title, distillation_method=distillation_method)

    extracted_candidates = [
        {
            "source_id": item.source_case_id,
            "task_family": item.task_family,
            "capability_id": item.capability_id,
            "title": item.title,
            "source_span": item.source_span,
            "matched_keywords": list(item.matched_keywords),
            "score": item.score,
            "selected": item.selected,
        }
        for item in projections
    ]
    capability_provenance = [
        {
            "capability_id": item.capability_id,
            "title": item.title,
            "task_family": item.task_family,
            "source_id": item.source_case_id,
            "source_span": item.source_span,
            "matched_keywords": list(item.matched_keywords),
            "projection_score": item.score,
            "selection_rule": "selected_when_keyword_projection_score_gt_zero",
        }
        for item in projections
    ]
    distillation_trace = {
        "generated_at": utc_now(),
        "skill_id": skill_id,
        "version": version,
        "method": distillation_method,
        "boundary": "This is bounded open-material distillation evidence over public or independent materials. It is not a claim of universal open-world semantic induction.",
        "steps": [
            {"stage": "load_source_materials", "artifact": "provenance/source_materials_manifest.json"},
            {"stage": "project_capabilities", "artifact": "provenance/extracted_candidates.json"},
            {"stage": "compile_runtime_manifest", "artifact": "manifest.json"},
            {"stage": "render_skill_text", "artifact": "SKILL.md"},
        ],
    }

    write_text(output_dir / "SKILL.md", render_root_skill_markdown(skill_id, versions, supported_families))
    write_json(output_dir / "manifest.json", root_manifest)
    write_text(
        output_dir / "README.md",
        "\n".join(
            [
                f"# {skill_id}",
                "",
                "This bundle was generated from open/public materials through bounded automatic distillation.",
                "",
                "```powershell",
                f"skill-deploy install --skill {output_dir.as_posix()} --version {version}",
                "```",
                "",
            ]
        )
        + "\n",
    )
    write_text(version_dir / "SKILL.md", version_skill)
    write_json(version_dir / "manifest.json", manifest)
    write_json(
        provenance_dir / "source_materials_manifest.json",
        {
            "sources": source_manifest,
            "source_count": len(source_manifest),
            "supported_task_families": supported_families,
            "distillation_scope": "bounded_open_materials",
        },
    )
    for material in materials:
        write_text(provenance_dir / "source_materials" / f"{material.source_id}.md", material.material_text + "\n")
    write_json(provenance_dir / "extracted_candidates.json", extracted_candidates)
    write_json(provenance_dir / "capability_provenance.json", capability_provenance)
    write_json(provenance_dir / "distillation_trace.json", distillation_trace)
    write_json(
        output_dir / "examples" / "distillation_summary.json",
        {
            "skill_id": skill_id,
            "version": version,
            "source_ids": [material.source_id for material in materials],
            "selected_capability_count": len({item.capability_id for item in projections}),
            "supported_task_families": supported_families,
            "distillation_scope": "bounded_open_materials",
        },
    )
    return {
        "skill_id": skill_id,
        "version": version,
        "output_dir": str(output_dir),
        "version_dir": str(version_dir),
        "supported_task_families": supported_families,
        "selected_capabilities": sorted({item.capability_id for item in projections}),
        "source_ids": [material.source_id for material in materials],
        "distillation_method": distillation_method,
    }
