from __future__ import annotations

import argparse
import difflib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = ROOT / "src"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from skill_deployment import SkillPackage, score_from_verifier  # noqa: E402
from skill_deployment.evidence import false_positive_count, write_json, write_text  # noqa: E402

import scripts.run_defensive_security_mini_suite as mini  # noqa: E402
from scripts.run_contract_improvement_demo import load_active, source_failure_rows  # noqa: E402
from scripts.run_external_generalization_validation import download_sources, materialize_cases  # noqa: E402


OUTPUT_ROOT = ROOT / "outputs" / "iterative_contract_improvement"
RUN_ROOT = ROOT / "outputs" / "iter_ci"
REPORT = ROOT / "reports" / "ITERATIVE_CONTRACT_IMPROVEMENT_STATUS.md"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def api_key_present() -> bool:
    return bool(os.environ.get("OPENAI_API_KEY"))


def read_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8-sig"))


def safe_failure_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for row in source_failure_rows():
        rows.append(
            {
                "source": row.get("source"),
                "case_id": row.get("case_id"),
                "task_family": row.get("task_family"),
                "activated_capability_group": row.get("activated_capability_group"),
                "feedback_type": row.get("feedback_type") or row.get("after_feedback_type"),
                "false_positive_count": row.get("false_positive_count"),
                "artifact_dir": row.get("artifact_dir"),
            }
        )
    return rows


def validation_cases() -> list[dict[str, Any]]:
    source_status = download_sources(RUN_ROOT / "validation_sources")
    cases = materialize_cases(source_status)
    wanted = {
        "public_nodegoat_dev_config_001",
        "independent_upload_mime_storage_001",
        "independent_upload_clean_001",
        "independent_config_prod_audit_001",
        "independent_auth_invoice_scope_001",
        "independent_api_schema_001",
        "independent_dependency_unsupported_001",
        "independent_ambiguous_debug_001",
    }
    return [case for case in cases if case["case_id"] in wanted]


def candidate_templates() -> list[dict[str, str]]:
    return [
        {
            "candidate_id": "c002_guard",
            "title": "Positive Observation Guard",
            "addition": """
## Iterative Contract Candidate: Positive Observation Guard

When an active capability line is already satisfied in the target, do not emit a finding for that capability. Treat these as evidence of existing controls, not as problems:

- content signature and extension are both checked
- server filename is generated by the server
- audit retention is configured to an explicit nonzero duration
- role/scope, tenant/owner filtering, or request-id-only denial envelopes are present
- audit retention and export sink are configured

If the model wants to mention a positive observation, put it in notes, not in findings. This narrows false-positive behavior and does not add new scope.
""".strip(),
        },
        {
            "candidate_id": "c003_auth",
            "title": "Auth Scope Matrix Precision",
            "addition": """
## Iterative Contract Candidate: Auth Scope Matrix Precision

For `auth_access_control`, evaluate the three auth capabilities separately:

- Emit `AUTH_SCOPE_MATRIX` when the target only checks authentication, but does not bind the operation to a role, scope, tenant, or permission matrix.
- Emit `AUTH_OBJECT_OWNERSHIP` when an object is loaded by id without tenant_id, owner_id, account_id, or equivalent ownership filtering.
- Emit `AUTH_ERROR_ENVELOPE` when denial or error output includes stable object identifiers or business ids instead of a neutral request id.

Do not apply this rule to clean targets that already include required role scope, tenant/owner filtering, and request-id-only denial output. Do not expand into dependency, regex, or server-side execution review.
""".strip(),
        },
        {
            "candidate_id": "c004_api",
            "title": "API Contract Precision",
            "addition": """
## Iterative Contract Candidate: API Contract Precision

For `api_or_code_review`, keep the two capabilities separate:

- Emit `API_SCHEMA_CONTRACT` when the target says a report builder emits prose or otherwise lacks required structured fields such as `capability_id`, `evidence_span`, or `recommended_fix`.
- Emit `API_OVERBROAD_RISK` when a risk label such as `debug_path` is asserted without a concrete target line, route, production caller, response field, or evidence span.

If a note says something *might* happen in the future but no route, caller, response schema, production path, or emitted field is shown, do not emit a concrete finding. Use no findings or low-confidence notes.
""".strip(),
        },
        {
            "candidate_id": "c005_cfg",
            "title": "Config Audit Precision",
            "addition": """
## Iterative Contract Candidate: Config Audit Precision

For `config_security`, keep audit export and environment guard distinct:

- Emit `CONFIG_AUDIT_EXPORT` when audit is enabled but retention duration, export sink, or reviewable audit destination is empty or missing.
- Emit `CONFIG_ENV_GUARD` only when a prod/release profile exposes secrets or a dev-only token is not clearly fenced to a development profile.

A dev-only token that is explicitly marked dev-only is not itself a production config finding. Do not add dependency/version-risk review to this skill.
""".strip(),
        },
        {
            "candidate_id": "c006_combo",
            "title": "Composed Low-Scope Contract Patch",
            "addition": """
## Iterative Contract Candidate: Composed Low-Scope Contract Patch

Apply the following narrow live-output discipline:

1. Positive observations are notes, not findings. Existing checks, generated filenames, configured retention, tenant/owner filters, role scopes, and request-id denial envelopes should not be reported as problems.
2. Auth findings must be separated into `AUTH_SCOPE_MATRIX`, `AUTH_OBJECT_OWNERSHIP`, and `AUTH_ERROR_ENVELOPE` only when exact target lines support each one.
3. API findings must distinguish missing structured output fields from overbroad risk labels. Future or hypothetical debug notes without route/schema/caller evidence should produce no concrete finding.
4. Config findings must distinguish missing audit export/retention from environment profile guard issues. Dev-only tokens are not production findings when they are explicitly fenced.
5. Unsupported dependency/version, regex DoS, and server-side execution review remain out of scope for `secure_code_review`.
""".strip(),
        },
    ]


def clone_candidate(base: SkillPackage, candidate_id: str) -> SkillPackage:
    metadata = json.loads(json.dumps(dict(base.metadata or {})))
    metadata["iterative_contract_candidate_id"] = candidate_id
    metadata["candidate_generation_sources"] = ["failure report", "verifier feedback", "evidence summary", "normalization trace"]
    metadata["verifier_only_oracle_fields_read"] = False
    metadata["scope_expansion_forbidden"] = True
    return SkillPackage(
        skill_id=base.skill_id,
        version=f"iterative_contract_{candidate_id}",
        task_family=base.task_family,
        capabilities=base.capabilities,
        output_contract=base.output_contract,
        trace_contract=base.trace_contract,
        metadata=metadata,
    )


def write_candidate(base: SkillPackage, base_text: str, template: dict[str, str], failures: list[dict[str, Any]]) -> tuple[mini.VariantSpec, Path]:
    candidate_id = template["candidate_id"]
    candidate_dir = RUN_ROOT / "cand" / candidate_id
    package = clone_candidate(base, candidate_id)
    text = base_text.rstrip() + "\n\n" + template["addition"].strip() + "\n"
    write_text(candidate_dir / "SKILL.md", text)
    write_json(candidate_dir / "manifest.json", package.to_dict())
    diff = "\n".join(difflib.unified_diff(base_text.splitlines(), text.splitlines(), fromfile="active_SKILL.md", tofile=f"{candidate_id}_SKILL.md", lineterm=""))
    write_text(
        candidate_dir / "skill_diff.md",
        "\n".join(
            [
                f"# Skill Diff: {candidate_id}",
                "",
                f"Targeted change: {template['title']}.",
                "",
                "## Evidence Binding",
                "",
                "- Generated from failure rows, verifier feedback, evidence summaries, and normalization traces.",
                "- Does not read verifier-only expected findings, expected evidence spans, or clean labels.",
                "- Does not add dependency/version-risk, regex DoS, or server-side execution review to core scope.",
                "",
                "## Candidate Patch",
                "",
                "```diff",
                diff,
                "```",
                "",
            ]
        ),
    )
    write_json(
        candidate_dir / "candidate_generation_inputs.json",
        {
            "candidate_id": candidate_id,
            "title": template["title"],
            "allowed_sources": ["failure report", "verifier feedback", "evidence summary", "normalization trace"],
            "forbidden_sources": ["verifier-only expected finding", "verifier-only expected evidence span", "verifier-only clean/negative answer label"],
            "verifier_only_oracle_fields_read": False,
            "failure_rows": failures,
        },
    )
    write_json(
        candidate_dir / "risk_assessment.json",
        {
            "scope_violation_risk": "medium" if candidate_id == "c006_combo" else "low",
            "dependency_version_risk_absorbed": False,
            "negative_control_required": True,
            "unsupported_limitation_required": True,
            "possible_regression": "over-reporting on ambiguous/clean rows",
        },
    )
    return mini.VariantSpec(candidate_id, package, text, candidate_dir, "iterative_contract_candidate"), candidate_dir


def run_case(
    *,
    case_payload: dict[str, Any],
    spec: mini.VariantSpec,
    pointer: dict[str, Any],
    output_dir: Path,
    base_url: str,
    model: str,
    timeout_seconds: float,
) -> dict[str, Any]:
    out_dir = output_dir / str(case_payload["case_id"]) / spec.name
    out_dir.mkdir(parents=True, exist_ok=True)
    if not api_key_present():
        return {"case_id": case_payload["case_id"], "variant": spec.name, "status": "blocked", "blocked_reason": "missing_env:OPENAI_API_KEY", "artifact_dir": str(out_dir)}
    try:
        summary = mini.run_variant(
            case_payload=case_payload,
            agent_case=mini.make_agent_visible_case(case_payload),
            verifier_only=case_payload["verifier_only"],
            spec=spec,
            backend="live_llm_text",
            output_dir=out_dir,
            active_pointer_snapshot=pointer,
            runner_metadata={
                "base_url": base_url,
                "model": model,
                "temperature": 0.0,
                "timeout": timeout_seconds,
                "task_label": f"secure_code_review:{case_payload['agent_visible']['task_family']}",
                "contract_mode": "strict",
                "enable_evidence_normalizer": True,
                "prompt_addendum": "Iterative candidate validation: quote exact target lines; emit no concrete finding for unsupported, clean, or ambiguous claims. Defensive review only.",
            },
        )
        verifier = summary.get("post_normalization_verifier") or summary.get("pre_normalization_verifier") or read_json(out_dir / "verifier_report.json", {})
        return {
            "case_id": case_payload["case_id"],
            "variant": spec.name,
            "status": "completed",
            "verifier_result": "pass" if verifier.get("pass") else "fail",
            "feedback_type": verifier.get("feedback_type"),
            "score": score_from_verifier(verifier),
            "false_positive_count": false_positive_count(verifier),
            "schema_error_count": len(verifier.get("schema_errors", [])),
            "unsupported_evidence_count": len(verifier.get("unsupported_evidence_capabilities", [])),
            "scope_violation": summary.get("activated_capability_group") != summary.get("expected_capability_group"),
            "out_of_scope_correct": summary.get("out_of_scope_correct"),
            "artifact_dir": str(out_dir),
        }
    except Exception as exc:  # noqa: BLE001
        write_text(out_dir / "blocked_or_failed_trace.txt", repr(exc))
        return {"case_id": case_payload["case_id"], "variant": spec.name, "status": "failed", "failure_reason": str(exc), "artifact_dir": str(out_dir)}


def decide_candidate(active_rows: list[dict[str, Any]], candidate_rows: list[dict[str, Any]]) -> tuple[dict[str, Any], dict[str, Any]]:
    active_by_case = {row["case_id"]: row for row in active_rows}
    candidate_by_case = {row["case_id"]: row for row in candidate_rows}
    shared_cases = [case_id for case_id in active_by_case if case_id in candidate_by_case]
    active_score = sum(float(active_by_case[case_id].get("score") or 0.0) for case_id in shared_cases) / len(shared_cases) if shared_cases else 0.0
    candidate_score = sum(float(candidate_by_case[case_id].get("score") or 0.0) for case_id in shared_cases) / len(shared_cases) if shared_cases else 0.0
    fp_delta = sum(int(candidate_by_case[case_id].get("false_positive_count") or 0) - int(active_by_case[case_id].get("false_positive_count") or 0) for case_id in shared_cases)
    schema_delta = sum(int(candidate_by_case[case_id].get("schema_error_count") or 0) - int(active_by_case[case_id].get("schema_error_count") or 0) for case_id in shared_cases)
    unsupported_delta = sum(int(candidate_by_case[case_id].get("unsupported_evidence_count") or 0) - int(active_by_case[case_id].get("unsupported_evidence_count") or 0) for case_id in shared_cases)
    scope_violation = any(bool(candidate_by_case[case_id].get("scope_violation")) for case_id in shared_cases)
    positive_regression_count = sum(
        1
        for case_id in shared_cases
        if active_by_case[case_id].get("verifier_result") == "pass"
        and candidate_by_case[case_id].get("verifier_result") != "pass"
        and "clean" not in case_id
        and "ambiguous" not in case_id
        and "unsupported" not in case_id
        and "dependency" not in case_id
    )
    clean_not_worse = all(
        int(candidate_by_case[case_id].get("false_positive_count") or 0) <= int(active_by_case[case_id].get("false_positive_count") or 0)
        for case_id in shared_cases
        if "clean" in case_id or "ambiguous" in case_id
    )
    unsupported_preserved = all(
        bool(candidate_by_case[case_id].get("out_of_scope_correct")) and int(candidate_by_case[case_id].get("false_positive_count") or 0) == 0
        for case_id in shared_cases
        if "dependency" in case_id or "unsupported" in case_id
    )
    validation = {
        "active_score": round(active_score, 4),
        "candidate_score": round(candidate_score, 4),
        "score_delta": round(candidate_score - active_score, 4),
        "false_positive_delta": fp_delta,
        "schema_error_delta": schema_delta,
        "unsupported_evidence_delta": unsupported_delta,
        "scope_violation": scope_violation,
        "positive_regression_count": positive_regression_count,
        "clean_negative_not_worse": clean_not_worse,
        "unsupported_limitation_preserved": unsupported_preserved,
        "shared_case_count": len(shared_cases),
    }
    promoted = (
        validation["score_delta"] > 0
        and fp_delta <= 0
        and schema_delta <= 0
        and unsupported_delta <= 0
        and not scope_violation
        and positive_regression_count == 0
        and clean_not_worse
        and unsupported_preserved
    )
    decision = {
        "decision": "staged_promotion_proposal" if promoted else "not_promoted",
        "reason": "strict_iterative_contract_rule_satisfied" if promoted else "strict_iterative_contract_rule_not_satisfied",
        "auto_installed": False,
        "promotion_rule": "candidate_score > active_score and false_positive_delta<=0 and schema_error_delta<=0 and unsupported_evidence_delta<=0 and positive_regression_count==0 and clean negative not worse and scope_violation=false",
    }
    return validation, decision


def render_report(payload: dict[str, Any]) -> str:
    lines = [
        "# Iterative Contract Improvement Status",
        "",
        f"Generated at: `{payload['generated_at']}`",
        "",
        f"- Candidate attempts: `{payload['candidate_count']}`",
        f"- Best candidate: `{payload.get('best_candidate_id')}`",
        f"- Evolution improvement: `{payload['evolution_improvement']}`",
        f"- Evolution maturity: `{payload['evolution_maturity']}`",
        f"- Promotion proposals: `{payload['promotion_proposal_count']}`",
        "",
        "## Candidate Decisions",
        "",
        "| Candidate | Decision | Active score | Candidate score | Delta | FP delta | Positive regressions | Clean not worse | Unsupported preserved |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for item in payload["candidates"]:
        validation = item["validation_result"]
        decision = item["promotion_decision"]
        lines.append(
            f"| {item['candidate_id']} | {decision['decision']} | {validation['active_score']} | {validation['candidate_score']} | "
            f"{validation['score_delta']} | {validation['false_positive_delta']} | {validation['positive_regression_count']} | "
            f"{validation['clean_negative_not_worse']} | {validation['unsupported_limitation_preserved']} |"
        )
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "- Candidates were generated only from failure reports, verifier feedback, evidence summaries, and normalization traces.",
            "- Verifier-only oracle fields were not read.",
            "- No candidate is auto-installed; staged promotion is a proposal requiring human review.",
            "- Dependency/version-risk, regex DoS, and server-side execution review remain out of scope.",
        ]
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Iteratively test narrow live contract candidates against strict promotion gates.")
    parser.add_argument("--installed", default="secure_code_review")
    parser.add_argument("--base-url", default=os.environ.get("OPENAI_BASE_URL") or "https://api.deepseek.com")
    parser.add_argument("--model", default=os.environ.get("MODEL") or os.environ.get("OPENAI_MODEL") or "deepseek-v4-flash")
    parser.add_argument("--timeout-seconds", type=float, default=60.0)
    parser.add_argument("--budget", type=int, default=5)
    args = parser.parse_args(argv)

    base, base_text, active_dir, pointer = load_active(args.installed)
    failures = safe_failure_rows()
    cases = validation_cases()
    active_spec = mini.VariantSpec("active", base, base_text, active_dir, "active_installed_package")
    active_rows = [
        run_case(
            case_payload=case_payload,
            spec=active_spec,
            pointer=pointer,
            output_dir=OUTPUT_ROOT / "active_baseline",
            base_url=args.base_url,
            model=args.model,
            timeout_seconds=args.timeout_seconds,
        )
        for case_payload in cases
    ]

    candidate_records: list[dict[str, Any]] = []
    for template in candidate_templates()[: max(0, args.budget)]:
        spec, candidate_dir = write_candidate(base, base_text, template, failures)
        rows = [
            run_case(
                case_payload=case_payload,
                spec=spec,
                pointer=pointer,
                output_dir=candidate_dir / "validation",
                base_url=args.base_url,
                model=args.model,
                timeout_seconds=args.timeout_seconds,
            )
            for case_payload in cases
        ]
        validation, decision = decide_candidate(active_rows, rows)
        write_json(candidate_dir / "validation_result.json", validation)
        write_json(candidate_dir / "promotion_decision.json", decision)
        record = {
            "candidate_id": template["candidate_id"],
            "title": template["title"],
            "candidate_dir": str(candidate_dir),
            "validation_result": validation,
            "promotion_decision": decision,
            "rows": rows,
        }
        write_json(candidate_dir / "candidate_summary.json", record)
        candidate_records.append(record)

    promotion_proposals = [item for item in candidate_records if item["promotion_decision"]["decision"] == "staged_promotion_proposal"]
    sorted_records = sorted(candidate_records, key=lambda item: (float(item["validation_result"]["score_delta"]), -int(item["validation_result"]["false_positive_delta"])), reverse=True)
    best = (sorted(promotion_proposals, key=lambda item: float(item["validation_result"]["score_delta"]), reverse=True)[0] if promotion_proposals else (sorted_records[0] if sorted_records else None))
    payload = {
        "run_id": "iterative_contract_improvement",
        "generated_at": utc_now(),
        "installed_skill": args.installed,
        "model": args.model,
        "api_key_present": api_key_present(),
        "candidate_count": len(candidate_records),
        "best_candidate_id": best["candidate_id"] if best else None,
        "promotion_proposal_count": len(promotion_proposals),
        "candidate_generation": "pass" if candidate_records else "blocked",
        "evolution_safety_gate": "pass" if candidate_records else "blocked",
        "evolution_improvement": "demonstrated" if promotion_proposals else "not_yet_demonstrated",
        "evolution_maturity": "improvement_demonstrated" if promotion_proposals else "safety_gate_pass",
        "active_rows": active_rows,
        "candidates": candidate_records,
        "claim_boundary": "iterative live-contract improvement; staged proposal only, no auto installation",
    }
    write_json(OUTPUT_ROOT / "iterative_contract_improvement_summary.json", payload)
    write_text(REPORT, render_report(payload))
    print(
        json.dumps(
            {
                "summary": str(OUTPUT_ROOT / "iterative_contract_improvement_summary.json"),
                "report": str(REPORT),
                "evolution_improvement": payload["evolution_improvement"],
                "promotion_proposal_count": payload["promotion_proposal_count"],
                "best_candidate_id": payload["best_candidate_id"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
